stages:
  - test
  - build
  - release

variables:
  REPO_SERVER_HOST: ${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}


build app:
  image: docker:20.10
  services:
    - docker:20.10-dind
  stage: build
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    GIT_ROOT_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME/packages/backuping
  before_script:
    - apk --no-cache add git
    - cd $GIT_ROOT_PATH
    - rm -fr base && git clone --depth 1 ${REPO_SERVER_HOST}/jalno/base.git base
    - cd ${GIT_ROOT_PATH} && cp -Rf base/* . && cd packages
    - rm -fr PhpParser && git clone --depth 1 ${REPO_SERVER_HOST}/yeganemehr/PhpParser.git
    - rm -fr phpmailer && git clone --depth 1 ${REPO_SERVER_HOST}/hosni/phpmailer.git
    - rm -fr dockerize && git clone --depth 1 ${REPO_SERVER_HOST}/yeganemehr/dockerize.git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd $GIT_ROOT_PATH
    - cp packages/dockerize/.dockerignore .
    - docker build --pull -f packages/backuping/Dockerfile -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

static analyse:
  image: registry.git.jeyserver.com/jalno/phpstan:master
  stage: test
  variables:
    GIT_ROOT_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME/packages/backuping
  before_script:
    - cd $GIT_ROOT_PATH
    - rm -fr base && git clone --depth 1 ${REPO_SERVER_HOST}/jalno/base.git base
    - cd ${GIT_ROOT_PATH} && cp -Rf base/* . && cd packages
    - rm -fr PhpParser && git clone --depth 1 ${REPO_SERVER_HOST}/yeganemehr/PhpParser.git
    - rm -fr phpmailer && git clone --depth 1 ${REPO_SERVER_HOST}/hosni/phpmailer.git
    - rm -fr cronjob && git clone --depth 1 ${REPO_SERVER_HOST}/yeganemehr/cronjob.git
    - rm -fr finder && git clone --depth 1 ${REPO_SERVER_HOST}/hosni/finder.git
  script:
    - phpstan analyse -c $GIT_CLONE_PATH/phpstan.neon $GIT_CLONE_PATH