#!/bin/sh

if [ -z "$1" ]
then
	php /var/www/html/index.php --process=packages/backuping/processes/Backuping@help
elif [ "$1" != "help" ] && [ "$1" != "backup" ] && [ "$1" != "restore" ] && [ "$1" != "cleanup" ]
then
	echo "backuping: '$1' is not a backuping command!"
	echo "See 'backuping help'"
else
	php /var/www/html/index.php --process=packages/backuping/processes/Backuping@"$@"
fi
